apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  type: LoadBalancer  # or use NodePort if LoadBalancer is not supported
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
